### PR TITLE
IMG: Added favicons, IEEEMEC logo

### LINKED ISSUE #2: Create Favicon version of the MEC logo

### PR DESCRIPTION
**Pull request by vhawk19**
Resolved #2 

### Changes
- Added favicon file (img/favicon.ico)

### CODE REVIEW

**Comment by de-sh** [comment]
Hey, there's no need to make many copies for different clients, just one is enough.

**Comment by vhawk19** [comment]
okay,sure.

But wouldn't it be better if it was optimized for different clients.Its just a few lines of extra code in the HTML right?

**Comment by de-sh** [comment]
Let's just say that we're aiming for more performance than specifics at the moment

**Comment by de-sh** [comment]
@vhawk19 look at this.

>commit : added shortcut icon

When you push to the branch of your remote, i.e. origin, you are efficiently pushing to the PR you made. So, all changes as made till date will show up on the PR you made last. You don't have to make a new PR!

**Comment by de-sh** [comment]
Also, as I said, do a `git reset HEAD^`(You can also use the HEAD~1 notation or the hash, `078f74443c694fe619d302f567e8121dd1bae9d2` in this case) to move back in time and delete the files from existence within the git repo history. Then push with `git push origin develop -f` to make sure your remote refs are updated!

**Comment by de-sh** [comment]
Also see, the edit history of this PR to better understand how to write awesome PRs, that will easily get accepted. PRs and commits are also forms of documentation that need to be crafted well, if you are planning to contribute to a community project. :smile:

**Comment by de-sh** [comment]
Well done, nice work. Better craft your PRs in the future

**Pull request merged**
